# Generated by Django 4.0.8 on 2022-11-14 16:36

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_department_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='parent',
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=mptt.fields.TreeManyToManyField(blank=True, null=True, related_name='children', to='users.department'),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=mptt.fields.TreeManyToManyField(blank=True, null=True, to='users.department'),
        ),
    ]
