# Generated by Django 4.0.8 on 2022-11-14 16:45

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_department_employee_emp_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dep_employee',
            field=mptt.fields.TreeManyToManyField(to='users.employee'),
        ),
    ]
