# Generated by Django 4.0.8 on 2022-11-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_department_dep_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dep_employee',
            field=models.ManyToManyField(to='users.employee'),
        ),
    ]
