# Generated by Django 4.0.8 on 2022-11-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_department_dep_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='department',
            name='dep_employee',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emp_department',
        ),
        migrations.AddField(
            model_name='employee',
            name='departments',
            field=models.ManyToManyField(to='users.department'),
        ),
    ]
